Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -13,7 +13,7 @@ permissions:
 jobs:
   publish:
     runs-on: ubuntu-latest
-    if: ${{ github.repository == 'ItsKirby69/EntityAnno' }}
+    #if: ${{ github.repository == 'ItsKirby69/EntityAnno' }}
 
     steps:
     - uses: actions/checkout@v4
@@ -24,30 +24,32 @@ jobs:
         distribution: temurin
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v4
-    - name: Set Artifact Version
-      run: |
-        if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
-          # This is a release, so use the release's tag as the version.
-          echo "ARTIFACT_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
-        elif [ "${GITHUB_REF_TYPE}" = "branch" ] && [ "${GITHUB_REF_NAME}" = "main" ]; then
-          # This is a bleeding-edge, so use the short commit's hash as the version.
-          echo "ARTIFACT_VERSION=$(git rev-parse --short=10 HEAD)" >> $GITHUB_ENV
-        else
-          # Sanity checks.
-          echo "Error: Unsupported branch '${GITHUB_REF_NAME}' or ref type '${GITHUB_REF_TYPE}'" >&2
-          exit 1
-        fi
-    - name: Publish Artifacts
-      run: |
-        chmod +x gradlew
-        ./gradlew -P version="${ARTIFACT_VERSION}" -D maven.repo.local="$(pwd)/.out" publishToMavenLocal
+    - name: Build with Gradle
+      run: ./gradlew build
+    # - name: Set Artifact Version
+    #   run: |
+    #     if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
+    #       # This is a release, so use the release's tag as the version.
+    #       echo "ARTIFACT_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
+    #     elif [ "${GITHUB_REF_TYPE}" = "branch" ] && [ "${GITHUB_REF_NAME}" = "main" ]; then
+    #       # This is a bleeding-edge, so use the short commit's hash as the version.
+    #       echo "ARTIFACT_VERSION=$(git rev-parse --short=10 HEAD)" >> $GITHUB_ENV
+    #     else
+    #       # Sanity checks.
+    #       echo "Error: Unsupported branch '${GITHUB_REF_NAME}' or ref type '${GITHUB_REF_TYPE}'" >&2
+    #       exit 1
+    #     fi
+    # - name: Publish Artifacts
+    #   run: |
+    #     chmod +x gradlew
+    #     ./gradlew -P version="${ARTIFACT_VERSION}" -D maven.repo.local="$(pwd)/.out" publishToMavenLocal
         
-        git clone https://${{ secrets.MAVEN_TOKEN_GITHUB }}@github.com/ItsKirby69/EntityAnnoMaven.git --depth=1 ../EntityAnnoMaven
-        cp -r .out/* ../EntityAnnoMaven
-        cd ../EntityAnnoMaven
+    #     git clone https://${{ secrets.MAVEN_TOKEN_GITHUB }}@github.com/ItsKirby69/EntityAnnoMaven.git --depth=1 ../EntityAnnoMaven
+    #     cp -r .out/* ../EntityAnnoMaven
+    #     cd ../EntityAnnoMaven
         
-        git config user.name "GitHub Actions"
-        git config user.email "actions@github.com"
-        git add .
-        git commit -m "Publishing for ${ARTIFACT_VERSION}"
-        git push https://${{ secrets.MAVEN_TOKEN_GITHUB }}@github.com/ItsKirby69/EntityAnnoMaven.git
+    #     git config user.name "GitHub Actions"
+    #     git config user.email "actions@github.com"
+    #     git add .
+    #     git commit -m "Publishing for ${ARTIFACT_VERSION}"
+    #     git push https://${{ secrets.MAVEN_TOKEN_GITHUB }}@github.com/ItsKirby69/EntityAnnoMaven.git
